/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    listings: Listing;
    payments: Payment;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    affiliateId: AffiliateId;
    contactInfo: ContactInfo;
    googleAnalytics: GoogleAnalytic;
  };
  globalsSelect: {
    affiliateId: AffiliateIdSelect<false> | AffiliateIdSelect<true>;
    contactInfo: ContactInfoSelect<false> | ContactInfoSelect<true>;
    googleAnalytics: GoogleAnalyticsSelect<false> | GoogleAnalyticsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  template:
    | 'default'
    | 'terms'
    | 'promotions'
    | 'privacy'
    | 'cookies'
    | 'reviews'
    | 'listings'
    | 'vacancies'
    | 'homepage'
    | 'warranty'
    | 'finance';
  termsContent?: {};
  promotionsContent?: {};
  privacyContent?: {};
  cookiesContent?: {};
  reviewsContent?: {};
  listingsContent?: {};
  vacanciesContent?: {};
  content?: {};
  warrantyContent?: {};
  financeContent?: {};
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  roles?: ('admin' | 'user')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: string;
  /**
   * MAKE - MODEL - YEAR
   */
  title?: string | null;
  vehicle?: {
    ownershipCondition?: string | null;
    registration?: string | null;
    vin?: string | null;
    make?: string | null;
    model?: string | null;
    generation?: string | null;
    derivative?: string | null;
    derivativeId?: string | null;
    vehicleType?: string | null;
    trim?: string | null;
    bodyType?: string | null;
    fuelType?: string | null;
    transmissionType?: string | null;
    drivetrain?: string | null;
    seats?: number | null;
    doors?: number | null;
    cylinders?: number | null;
    co2EmissionGPKM?: number | null;
    topSpeedMPH?: number | null;
    zeroToSixtyMPHSeconds?: number | null;
    badgeEngineSizeLitres?: number | null;
    engineCapacityCC?: number | null;
    enginePowerBHP?: number | null;
    fuelCapacityLitres?: number | null;
    emissionClass?: string | null;
    owners?: number | null;
    fuelEconomyNEDCCombinedMPG?: number | null;
    fuelEconomyWLTPCombinedMPG?: number | null;
    bootSpaceSeatsUpLitres?: number | null;
    insuranceGroup?: string | null;
    firstRegistrationDate?: string | null;
    colour?: string | null;
    style?: string | null;
    odometerReadingMiles?: number | null;
    motExpiryDate?: string | null;
    warrantyMonthsOnPurchase?: number | null;
    serviceHistory?: string | null;
    plate?: string | null;
    yearOfManufacture?: number | null;
    standard?: {
      make?: string | null;
      model?: string | null;
      generation?: string | null;
      derivative?: string | null;
      trim?: string | null;
      bodyType?: string | null;
      fuelType?: string | null;
      transmissionType?: string | null;
      colour?: string | null;
      style?: string | null;
    };
  };
  advertiser?: {
    advertiserId?: string | null;
    name?: string | null;
    segment?: string | null;
    website?: string | null;
    phone?: string | null;
    location?: {
      addressLineOne?: string | null;
      town?: string | null;
      county?: string | null;
      region?: string | null;
      postCode?: string | null;
      latitude?: number | null;
      longitude?: number | null;
    };
  };
  adverts?: {
    forecourtPrice?: {
      amountGBP?: number | null;
    };
    soldPrice?: {
      amountGBP?: number | null;
    };
    forecourtPriceVatStatus?: string | null;
    vatScheme?: string | null;
    dueDate?: string | null;
    manufacturerApproved?: boolean | null;
    twelveMonthsMot?: boolean | null;
    motInsurance?: string | null;
    reservationStatus?: string | null;
    retailAdverts?: {
      priceOnApplication?: boolean | null;
      suppliedPrice?: {
        amountGBP?: number | null;
        amountGBX?: number | null;
      };
      totalPrice?: {
        amountGBP?: number | null;
      };
      reservePrice?: number | null;
      adminFee?: {
        amountGBP?: number | null;
      };
      adminFeeOverride?: {
        amountGBP?: number | null;
      };
      manufacturerRRP?: {
        amountGBP?: number | null;
      };
      vatStatus?: string | null;
      attentionGrabber?: string | null;
      description?: string | null;
      description2?: string | null;
      priceIndicatorRating?: string | null;
      priceIndicatorRatingBands?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
      autotraderAdvert?: {
        status?: string | null;
        eligibleContractAllowances?:
          | {
              type?: string | null;
              id?: string | null;
            }[]
          | null;
        allocatedContractAllowance?: {
          type?: string | null;
        };
      };
      advertiserAdvert?: {
        status?: string | null;
      };
      locatorAdvert?: {
        status?: string | null;
      };
      exportAdvert?: {
        status?: string | null;
      };
      profileAdvert?: {
        status?: string | null;
      };
      displayOptions?: {
        excludePreviousOwners?: boolean | null;
        excludeStrapline?: boolean | null;
        excludeMot?: boolean | null;
        excludeWarranty?: boolean | null;
        excludeInteriorDetails?: boolean | null;
        excludeTyreCondition?: boolean | null;
        excludeBodyCondition?: boolean | null;
      };
      financeOffers?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    tradeAdverts?: {
      dealerAuctionAdvert?: {
        status?: string | null;
      };
    };
  };
  metadata?: {
    stockId?: string | null;
    searchId?: string | null;
    externalStockId?: string | null;
    lastUpdated?: string | null;
    versionNumber?: number | null;
    lifecycleState?: string | null;
    dateOnForecourt?: string | null;
  };
  features?:
    | {
        name?: string | null;
        type?: string | null;
        standardName?: string | null;
        category?: string | null;
        rarityRating?: string | null;
        valueRating?: string | null;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        highlight?: string | null;
        id?: string | null;
      }[]
    | null;
  media?: {
    images?:
      | {
          href?: string | null;
          templated?: boolean | null;
          id?: string | null;
        }[]
      | null;
    video?: {
      href?: string | null;
    };
    spin?: {
      href?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: string;
  customerDetails?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  vehicleDetails?: {
    make?: string | null;
    model?: string | null;
    registration?: string | null;
    stockId?: string | null;
  };
  /**
   * Amount in GBP (pence)
   */
  amount?: number | null;
  currency?: string | null;
  atoaPaymentDetails?: {
    paymentRequestId?: string | null;
    orderId?: string | null;
    customerId?: string | null;
    paymentUrl?: string | null;
    qrCodeUrl?: string | null;
    paymentIdempotencyId?: string | null;
  };
  paymentStatus?: ('PENDING' | 'COMPLETED' | 'FAILED' | 'EXPIRED' | 'CANCELLED') | null;
  statusDetails?: {
    statusUpdateDate?: string | null;
    isoStatus?: {
      code?: string | null;
      name?: string | null;
    };
    errorDescription?: string | null;
  };
  /**
   * Actual amount paid in GBP (pence)
   */
  paidAmount?: number | null;
  /**
   * Tip amount in GBP (pence)
   */
  tipAmount?: number | null;
  customerName?: string | null;
  signatureHash?: string | null;
  reservationMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'listings';
        value: string | Listing;
      } | null)
    | ({
        relationTo: 'payments';
        value: string | Payment;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  template?: T;
  termsContent?: T | {};
  promotionsContent?: T | {};
  privacyContent?: T | {};
  cookiesContent?: T | {};
  reviewsContent?: T | {};
  listingsContent?: T | {};
  vacanciesContent?: T | {};
  content?: T | {};
  warrantyContent?: T | {};
  financeContent?: T | {};
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  title?: T;
  vehicle?:
    | T
    | {
        ownershipCondition?: T;
        registration?: T;
        vin?: T;
        make?: T;
        model?: T;
        generation?: T;
        derivative?: T;
        derivativeId?: T;
        vehicleType?: T;
        trim?: T;
        bodyType?: T;
        fuelType?: T;
        transmissionType?: T;
        drivetrain?: T;
        seats?: T;
        doors?: T;
        cylinders?: T;
        co2EmissionGPKM?: T;
        topSpeedMPH?: T;
        zeroToSixtyMPHSeconds?: T;
        badgeEngineSizeLitres?: T;
        engineCapacityCC?: T;
        enginePowerBHP?: T;
        fuelCapacityLitres?: T;
        emissionClass?: T;
        owners?: T;
        fuelEconomyNEDCCombinedMPG?: T;
        fuelEconomyWLTPCombinedMPG?: T;
        bootSpaceSeatsUpLitres?: T;
        insuranceGroup?: T;
        firstRegistrationDate?: T;
        colour?: T;
        style?: T;
        odometerReadingMiles?: T;
        motExpiryDate?: T;
        warrantyMonthsOnPurchase?: T;
        serviceHistory?: T;
        plate?: T;
        yearOfManufacture?: T;
        standard?:
          | T
          | {
              make?: T;
              model?: T;
              generation?: T;
              derivative?: T;
              trim?: T;
              bodyType?: T;
              fuelType?: T;
              transmissionType?: T;
              colour?: T;
              style?: T;
            };
      };
  advertiser?:
    | T
    | {
        advertiserId?: T;
        name?: T;
        segment?: T;
        website?: T;
        phone?: T;
        location?:
          | T
          | {
              addressLineOne?: T;
              town?: T;
              county?: T;
              region?: T;
              postCode?: T;
              latitude?: T;
              longitude?: T;
            };
      };
  adverts?:
    | T
    | {
        forecourtPrice?:
          | T
          | {
              amountGBP?: T;
            };
        soldPrice?:
          | T
          | {
              amountGBP?: T;
            };
        forecourtPriceVatStatus?: T;
        vatScheme?: T;
        dueDate?: T;
        manufacturerApproved?: T;
        twelveMonthsMot?: T;
        motInsurance?: T;
        reservationStatus?: T;
        retailAdverts?:
          | T
          | {
              priceOnApplication?: T;
              suppliedPrice?:
                | T
                | {
                    amountGBP?: T;
                    amountGBX?: T;
                  };
              totalPrice?:
                | T
                | {
                    amountGBP?: T;
                  };
              reservePrice?: T;
              adminFee?:
                | T
                | {
                    amountGBP?: T;
                  };
              adminFeeOverride?:
                | T
                | {
                    amountGBP?: T;
                  };
              manufacturerRRP?:
                | T
                | {
                    amountGBP?: T;
                  };
              vatStatus?: T;
              attentionGrabber?: T;
              description?: T;
              description2?: T;
              priceIndicatorRating?: T;
              priceIndicatorRatingBands?: T;
              autotraderAdvert?:
                | T
                | {
                    status?: T;
                    eligibleContractAllowances?:
                      | T
                      | {
                          type?: T;
                          id?: T;
                        };
                    allocatedContractAllowance?:
                      | T
                      | {
                          type?: T;
                        };
                  };
              advertiserAdvert?:
                | T
                | {
                    status?: T;
                  };
              locatorAdvert?:
                | T
                | {
                    status?: T;
                  };
              exportAdvert?:
                | T
                | {
                    status?: T;
                  };
              profileAdvert?:
                | T
                | {
                    status?: T;
                  };
              displayOptions?:
                | T
                | {
                    excludePreviousOwners?: T;
                    excludeStrapline?: T;
                    excludeMot?: T;
                    excludeWarranty?: T;
                    excludeInteriorDetails?: T;
                    excludeTyreCondition?: T;
                    excludeBodyCondition?: T;
                  };
              financeOffers?: T;
            };
        tradeAdverts?:
          | T
          | {
              dealerAuctionAdvert?:
                | T
                | {
                    status?: T;
                  };
            };
      };
  metadata?:
    | T
    | {
        stockId?: T;
        searchId?: T;
        externalStockId?: T;
        lastUpdated?: T;
        versionNumber?: T;
        lifecycleState?: T;
        dateOnForecourt?: T;
      };
  features?:
    | T
    | {
        name?: T;
        type?: T;
        standardName?: T;
        category?: T;
        rarityRating?: T;
        valueRating?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        highlight?: T;
        id?: T;
      };
  media?:
    | T
    | {
        images?:
          | T
          | {
              href?: T;
              templated?: T;
              id?: T;
            };
        video?:
          | T
          | {
              href?: T;
            };
        spin?:
          | T
          | {
              href?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  customerDetails?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        email?: T;
        phone?: T;
        address?: T;
      };
  vehicleDetails?:
    | T
    | {
        make?: T;
        model?: T;
        registration?: T;
        stockId?: T;
      };
  amount?: T;
  currency?: T;
  atoaPaymentDetails?:
    | T
    | {
        paymentRequestId?: T;
        orderId?: T;
        customerId?: T;
        paymentUrl?: T;
        qrCodeUrl?: T;
        paymentIdempotencyId?: T;
      };
  paymentStatus?: T;
  statusDetails?:
    | T
    | {
        statusUpdateDate?: T;
        isoStatus?:
          | T
          | {
              code?: T;
              name?: T;
            };
        errorDescription?: T;
      };
  paidAmount?: T;
  tipAmount?: T;
  customerName?: T;
  signatureHash?: T;
  reservationMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage dealer affiliate IDs for the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliateId".
 */
export interface AffiliateId {
  id: string;
  affiliateIds?:
    | {
        /**
         * Enter the dealer affiliate ID
         */
        dealerAffiliateId: string;
        /**
         * Set this affiliate ID as active/inactive
         */
        isActive?: boolean | null;
        /**
         * Add a note about when or where this affiliate ID is used
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage phone numbers and social media links for the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactInfo".
 */
export interface ContactInfo {
  id: string;
  title?: string | null;
  phoneNumbers?:
    | {
        label: string;
        number: string;
        /**
         * Mark this as the main phone number
         */
        isPrimary?: boolean | null;
        id?: string | null;
      }[]
    | null;
  whatsappNumber?: string | null;
  socialLinks?:
    | {
        platform:
          | 'facebook'
          | 'twitter'
          | 'instagram'
          | 'linkedin'
          | 'youtube'
          | 'tiktok'
          | 'whatsapp'
          | 'google'
          | 'other';
        /**
         * Enter the platform name when "Other" is selected
         */
        customPlatform?: string | null;
        url: string;
        /**
         * Uncheck to hide this social link from the website
         */
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  emailAddresses?:
    | {
        label: string;
        email: string;
        /**
         * Mark this as the main email address
         */
        isPrimary?: boolean | null;
        id?: string | null;
      }[]
    | null;
  businessAddress?: {
    name?: string | null;
    street?: string | null;
    city?: string | null;
    postcode?: string | null;
    country?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage Google Analytics for the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "googleAnalytics".
 */
export interface GoogleAnalytic {
  id: string;
  /**
   * Enter the Google Analytics ID (G-XXXXXXX)
   */
  googleAnalyticsId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliateId_select".
 */
export interface AffiliateIdSelect<T extends boolean = true> {
  affiliateIds?:
    | T
    | {
        dealerAffiliateId?: T;
        isActive?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactInfo_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  title?: T;
  phoneNumbers?:
    | T
    | {
        label?: T;
        number?: T;
        isPrimary?: T;
        id?: T;
      };
  whatsappNumber?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        customPlatform?: T;
        url?: T;
        isActive?: T;
        id?: T;
      };
  emailAddresses?:
    | T
    | {
        label?: T;
        email?: T;
        isPrimary?: T;
        id?: T;
      };
  businessAddress?:
    | T
    | {
        name?: T;
        street?: T;
        city?: T;
        postcode?: T;
        country?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "googleAnalytics_select".
 */
export interface GoogleAnalyticsSelect<T extends boolean = true> {
  googleAnalyticsId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}